# Site settings
title: CoderDojo @ LibertyGlobal
short-title: CD@LG
email: phalliday@libertyglobal.com
url: https://libertyglobal-coderdojo.github.io
description: "Links and information supporting CoderDojo events organized by Liberty Global"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Liberty Global
  social: Github
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/LibertyGlobal-CoderDojo

# Credits content
credits: 'Site source adapted from Freelancer. A free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# Exclude these files
exclude: [
  README.md,
  Gemfile,
  Gemfile.lock,
  LICENCE,
  prepare.sh,
  start.sh,
  img_src
]

# short URLS
permalink: :categories/:title/

# syntax highlighting
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter: rouge

# plugins
gems:
  - jekyll-sitemap

# sections
sections: [{
  id: 'projects',
  title: 'Projects',
  category: 'project'
}, {
  id: 'events',
  title: 'Events',
  category: 'event'
}]
